// Code generated by go-bindata.
// sources:
// ui/dist/ui/3rdpartylicenses.txt
// ui/dist/ui/favicon.ico
// ui/dist/ui/index.html
// ui/dist/ui/main.js
// ui/dist/ui/main.js.map
// ui/dist/ui/polyfills.js
// ui/dist/ui/polyfills.js.map
// ui/dist/ui/runtime.js
// ui/dist/ui/runtime.js.map
// ui/dist/ui/styles.js
// ui/dist/ui/styles.js.map
// ui/dist/ui/vendor.js
// ui/dist/ui/vendor.js.map
// DO NOT EDIT!

package api

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// _3rdpartylicensesTxt reads file data from disk. It returns an error on failure.
func _3rdpartylicensesTxt() (*asset, error) {
	path := "/Users/dkostenko/go/src/github.com/dkostenko/plantuml/ui/dist/ui/3rdpartylicenses.txt"
	name := "3rdpartylicenses.txt"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// faviconIco reads file data from disk. It returns an error on failure.
func faviconIco() (*asset, error) {
	path := "/Users/dkostenko/go/src/github.com/dkostenko/plantuml/ui/dist/ui/favicon.ico"
	name := "favicon.ico"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// indexHtml reads file data from disk. It returns an error on failure.
func indexHtml() (*asset, error) {
	path := "/Users/dkostenko/go/src/github.com/dkostenko/plantuml/ui/dist/ui/index.html"
	name := "index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// mainJs reads file data from disk. It returns an error on failure.
func mainJs() (*asset, error) {
	path := "/Users/dkostenko/go/src/github.com/dkostenko/plantuml/ui/dist/ui/main.js"
	name := "main.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// mainJsMap reads file data from disk. It returns an error on failure.
func mainJsMap() (*asset, error) {
	path := "/Users/dkostenko/go/src/github.com/dkostenko/plantuml/ui/dist/ui/main.js.map"
	name := "main.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// polyfillsJs reads file data from disk. It returns an error on failure.
func polyfillsJs() (*asset, error) {
	path := "/Users/dkostenko/go/src/github.com/dkostenko/plantuml/ui/dist/ui/polyfills.js"
	name := "polyfills.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// polyfillsJsMap reads file data from disk. It returns an error on failure.
func polyfillsJsMap() (*asset, error) {
	path := "/Users/dkostenko/go/src/github.com/dkostenko/plantuml/ui/dist/ui/polyfills.js.map"
	name := "polyfills.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// runtimeJs reads file data from disk. It returns an error on failure.
func runtimeJs() (*asset, error) {
	path := "/Users/dkostenko/go/src/github.com/dkostenko/plantuml/ui/dist/ui/runtime.js"
	name := "runtime.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// runtimeJsMap reads file data from disk. It returns an error on failure.
func runtimeJsMap() (*asset, error) {
	path := "/Users/dkostenko/go/src/github.com/dkostenko/plantuml/ui/dist/ui/runtime.js.map"
	name := "runtime.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// stylesJs reads file data from disk. It returns an error on failure.
func stylesJs() (*asset, error) {
	path := "/Users/dkostenko/go/src/github.com/dkostenko/plantuml/ui/dist/ui/styles.js"
	name := "styles.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// stylesJsMap reads file data from disk. It returns an error on failure.
func stylesJsMap() (*asset, error) {
	path := "/Users/dkostenko/go/src/github.com/dkostenko/plantuml/ui/dist/ui/styles.js.map"
	name := "styles.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorJs reads file data from disk. It returns an error on failure.
func vendorJs() (*asset, error) {
	path := "/Users/dkostenko/go/src/github.com/dkostenko/plantuml/ui/dist/ui/vendor.js"
	name := "vendor.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorJsMap reads file data from disk. It returns an error on failure.
func vendorJsMap() (*asset, error) {
	path := "/Users/dkostenko/go/src/github.com/dkostenko/plantuml/ui/dist/ui/vendor.js.map"
	name := "vendor.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"3rdpartylicenses.txt": _3rdpartylicensesTxt,
	"favicon.ico": faviconIco,
	"index.html": indexHtml,
	"main.js": mainJs,
	"main.js.map": mainJsMap,
	"polyfills.js": polyfillsJs,
	"polyfills.js.map": polyfillsJsMap,
	"runtime.js": runtimeJs,
	"runtime.js.map": runtimeJsMap,
	"styles.js": stylesJs,
	"styles.js.map": stylesJsMap,
	"vendor.js": vendorJs,
	"vendor.js.map": vendorJsMap,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"3rdpartylicenses.txt": &bintree{_3rdpartylicensesTxt, map[string]*bintree{}},
	"favicon.ico": &bintree{faviconIco, map[string]*bintree{}},
	"index.html": &bintree{indexHtml, map[string]*bintree{}},
	"main.js": &bintree{mainJs, map[string]*bintree{}},
	"main.js.map": &bintree{mainJsMap, map[string]*bintree{}},
	"polyfills.js": &bintree{polyfillsJs, map[string]*bintree{}},
	"polyfills.js.map": &bintree{polyfillsJsMap, map[string]*bintree{}},
	"runtime.js": &bintree{runtimeJs, map[string]*bintree{}},
	"runtime.js.map": &bintree{runtimeJsMap, map[string]*bintree{}},
	"styles.js": &bintree{stylesJs, map[string]*bintree{}},
	"styles.js.map": &bintree{stylesJsMap, map[string]*bintree{}},
	"vendor.js": &bintree{vendorJs, map[string]*bintree{}},
	"vendor.js.map": &bintree{vendorJsMap, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

